### ISSUE TITLE
感谢大神~~ 有一个添加的定位问题

### ISSUE THREAD

**Issue by errolsong** [jaynaruto/discuzxsso#1]
老大只有一个问题，前面都很顺利的完成下列了，到下面这里

---

7.修改wiki目录/includes/specials/SpecialUserLogin.php，第900行return self::SUCCESS;之前添加如下代码：echo "<script>location.reload();</script>";//解决新用户第一次登录wiki白板问题

---

我的1.24但900行并不是return self::SUCCESS;，所以想知道这个return self::SUCCESS;附近几行的代码以便准确定位，因为附近好多return self::SUCCESS;。。。。

**Comment by savokiss** [comment]
啊。。用行定位确实不太好找，是在`attemptAutoCreate`这个方法的最后一行有个`return self::SUCCESS;`，在这句前面加上那个`echo`嗯
